apiVersion: v1
kind: Namespace
metadata:
  name: careloop-dev
  labels:
    environment: dev
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: careloop-staging
  labels:
    environment: staging
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: careloop-prod
  labels:
    environment: prod
    pod-security.kubernetes.io/enforce: restricted
