/**
 * Demo Sample Data
 * Realistic patient data for demo purposes
 */

// Simplified demo patient type
export interface DemoPatient {
  id: string;
  first_name: string;
  last_name: string;
  date_of_birth: string;
  age: number;
  gender: 'male' | 'female' | 'other';
  email: string;
  phone: string;
  address?: string;
  primary_doctor_id: string;
  primary_doctor_name: string;
  last_visit_date?: string;
  next_appointment_date?: string;
  profile_image_url?: string;
  has_allergies?: boolean;
  requires_pre_medication?: boolean;
  has_outstanding_balance?: boolean;
}

// Sample patients for demo
export const DEMO_PATIENTS: DemoPatient[] = [
  {
    id: 'demo-p-001',
    first_name: 'Sarah',
    last_name: 'Johnson',
    date_of_birth: '1985-03-15',
    age: 40,
    gender: 'female',
    email: 'sarah.johnson@email.com',
    phone: '+16195551234',
    address: '123 Oak Street, San Diego, CA 92101',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-09-15',
    next_appointment_date: '2025-10-25T14:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-002',
    first_name: 'Michael',
    last_name: 'Rodriguez',
    date_of_birth: '1978-07-22',
    age: 47,
    gender: 'male',
    email: 'michael.r@email.com',
    phone: '+16195552345',
    address: '456 Pine Avenue, San Diego, CA 92102',
    primary_doctor_id: 'doc-002',
    primary_doctor_name: 'Dr. James Wilson',
    last_visit_date: '2025-10-10',
    next_appointment_date: '2025-11-05T10:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    has_allergies: true,
    requires_pre_medication: false,
    has_outstanding_balance: true,
  },
  {
    id: 'demo-p-003',
    first_name: 'Emily',
    last_name: 'Chen',
    date_of_birth: '1992-11-08',
    age: 32,
    gender: 'female',
    email: 'emily.chen@email.com',
    phone: '+16195553456',
    address: '789 Maple Drive, San Diego, CA 92103',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-10-12',
    next_appointment_date: '2025-10-28T15:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-004',
    first_name: 'David',
    last_name: 'Thompson',
    date_of_birth: '1965-05-30',
    age: 60,
    gender: 'male',
    email: 'david.t@email.com',
    phone: '+16195554567',
    address: '321 Birch Lane, San Diego, CA 92104',
    primary_doctor_id: 'doc-003',
    primary_doctor_name: 'Dr. Sarah Martinez',
    last_visit_date: '2025-08-20',
    next_appointment_date: '2025-10-30T09:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    has_allergies: false,
    requires_pre_medication: true,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-005',
    first_name: 'Jennifer',
    last_name: 'Lee',
    date_of_birth: '1988-09-12',
    age: 37,
    gender: 'female',
    email: 'jennifer.lee@email.com',
    phone: '+16195555678',
    address: '654 Cedar Court, San Diego, CA 92105',
    primary_doctor_id: 'doc-002',
    primary_doctor_name: 'Dr. James Wilson',
    last_visit_date: '2025-10-05',
    next_appointment_date: '2025-11-15T13:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer',
    has_allergies: true,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-006',
    first_name: 'Robert',
    last_name: 'Martinez',
    date_of_birth: '1972-01-25',
    age: 53,
    gender: 'male',
    email: 'robert.m@email.com',
    phone: '+16195556789',
    address: '987 Elm Street, San Diego, CA 92106',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-09-28',
    next_appointment_date: '2025-10-22T11:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: true,
  },
  {
    id: 'demo-p-007',
    first_name: 'Amanda',
    last_name: 'Taylor',
    date_of_birth: '1995-04-18',
    age: 30,
    gender: 'female',
    email: 'amanda.t@email.com',
    phone: '+16195557890',
    address: '147 Willow Way, San Diego, CA 92107',
    primary_doctor_id: 'doc-003',
    primary_doctor_name: 'Dr. Sarah Martinez',
    last_visit_date: '2025-10-14',
    next_appointment_date: '2025-11-02T14:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-008',
    first_name: 'Christopher',
    last_name: 'Anderson',
    date_of_birth: '1980-12-03',
    age: 44,
    gender: 'male',
    email: 'chris.anderson@email.com',
    phone: '+16195558901',
    address: '258 Spruce Street, San Diego, CA 92108',
    primary_doctor_id: 'doc-002',
    primary_doctor_name: 'Dr. James Wilson',
    last_visit_date: '2025-09-22',
    next_appointment_date: '2025-10-27T10:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-009',
    first_name: 'Lisa',
    last_name: 'White',
    date_of_birth: '1990-06-14',
    age: 35,
    gender: 'female',
    email: 'lisa.white@email.com',
    phone: '+16195559012',
    address: '369 Ash Avenue, San Diego, CA 92109',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-10-08',
    next_appointment_date: '2025-11-10T15:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    has_allergies: true,
    requires_pre_medication: true,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-010',
    first_name: 'James',
    last_name: 'Brown',
    date_of_birth: '1968-08-27',
    age: 57,
    gender: 'male',
    email: 'james.brown@email.com',
    phone: '+16195550123',
    address: '741 Poplar Place, San Diego, CA 92110',
    primary_doctor_id: 'doc-003',
    primary_doctor_name: 'Dr. Sarah Martinez',
    last_visit_date: '2025-09-30',
    next_appointment_date: '2025-10-24T09:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-011',
    first_name: 'Patricia',
    last_name: 'Garcia',
    date_of_birth: '1987-02-19',
    age: 38,
    gender: 'female',
    email: 'patricia.g@email.com',
    phone: '+16195551234',
    address: '852 Hickory Hill, San Diego, CA 92111',
    primary_doctor_id: 'doc-002',
    primary_doctor_name: 'Dr. James Wilson',
    last_visit_date: '2025-10-11',
    next_appointment_date: '2025-11-08T11:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: true,
  },
  {
    id: 'demo-p-012',
    first_name: 'Daniel',
    last_name: 'Miller',
    date_of_birth: '1975-10-05',
    age: 50,
    gender: 'male',
    email: 'daniel.miller@email.com',
    phone: '+16195552345',
    address: '963 Redwood Road, San Diego, CA 92112',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-09-25',
    next_appointment_date: '2025-10-29T14:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-013',
    first_name: 'Nancy',
    last_name: 'Wilson',
    date_of_birth: '1993-07-11',
    age: 32,
    gender: 'female',
    email: 'nancy.wilson@email.com',
    phone: '+16195553456',
    address: '159 Magnolia Street, San Diego, CA 92113',
    primary_doctor_id: 'doc-003',
    primary_doctor_name: 'Dr. Sarah Martinez',
    last_visit_date: '2025-10-13',
    next_appointment_date: '2025-11-12T10:00:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nancy',
    has_allergies: true,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-014',
    first_name: 'Kevin',
    last_name: 'Moore',
    date_of_birth: '1982-03-28',
    age: 43,
    gender: 'male',
    email: 'kevin.moore@email.com',
    phone: '+16195554567',
    address: '357 Dogwood Drive, San Diego, CA 92114',
    primary_doctor_id: 'doc-002',
    primary_doctor_name: 'Dr. James Wilson',
    last_visit_date: '2025-10-07',
    next_appointment_date: '2025-11-01T13:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    has_allergies: false,
    requires_pre_medication: false,
    has_outstanding_balance: false,
  },
  {
    id: 'demo-p-015',
    first_name: 'Karen',
    last_name: 'Davis',
    date_of_birth: '1970-11-16',
    age: 55,
    gender: 'female',
    email: 'karen.davis@email.com',
    phone: '+16195555678',
    address: '486 Sycamore Lane, San Diego, CA 92115',
    primary_doctor_id: 'doc-001',
    primary_doctor_name: 'Dr. Emily Chen',
    last_visit_date: '2025-09-18',
    next_appointment_date: '2025-10-26T15:30:00Z',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karen',
    has_allergies: false,
    requires_pre_medication: true,
    has_outstanding_balance: false,
  },
];

// Demo login credentials
export const DEMO_USERS = [
  {
    email: 'admin@careloop.demo',
    password: 'demo123',
    role: 'admin' as const,
    name: 'Admin Demo User',
  },
  {
    email: 'doctor@careloop.demo',
    password: 'demo123',
    role: 'doctor' as const,
    name: 'Dr. Emily Chen',
  },
  {
    email: 'nurse@careloop.demo',
    password: 'demo123',
    role: 'nurse' as const,
    name: 'Sarah Nurse',
  },
  {
    email: 'receptionist@careloop.demo',
    password: 'demo123',
    role: 'receptionist' as const,
    name: 'John Receptionist',
  },
];

// Helper to check if in demo mode
export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  const email = localStorage.getItem('demo_user_email');
  return email?.endsWith('@careloop.demo') || false;
}

// Get demo patient by ID
export function getDemoPatient(patientId: string): DemoPatient | undefined {
  return DEMO_PATIENTS.find(p => p.id === patientId);
}

// Get all demo patients
export function getAllDemoPatients(): DemoPatient[] {
  return DEMO_PATIENTS;
}
