apiVersion: v1
kind: Service
metadata:
  name: careloop-web
  namespace: careloop-staging
spec:
  selector:
    app: careloop-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
